name: forecasting-electricity
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy[version='<2']
  - matplotlib
  - seaborn
  - ipykernel
  - notebook
  - scipy
  - scikit-learn
  - plotly
  - jupyterlab
  - pytest
  - statsmodels
  - pyarrow
  - fastparquet
  - umap-learn
  - tqdm
  - ipywidgets
  - tensorboard
  - streamlit
  - python-dotenv
  - pyyaml
  - holidays
  - pytorch
  - lightning
  - pytorch-lightning
  - pytorch-forecasting
  - gluonts
  - xgboost
  - lightgbm
  - prophet
  - openai
